`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Generated by ChatGPT
//////////////////////////////////////////////////////////////////////////////////


module binary_to_bcd (
    input [5:0] BINARY,   // 6-bitowe wejœcie binarne
    output reg [3:0] BCD1, // 4-bitowy BCD dla pierwszej cyfry
    output reg [3:0] BCD2  // 4-bitowy BCD dla drugiej cyfry
);

    integer i;

    always @(*) begin
        // Pocz¹tkowe ustawienie BCD
        BCD1 = 4'b0000; 
        BCD2 = 4'b0000;

        // Proces konwersji binarnej na BCD
        for (i = 5; i >= 0; i = i - 1) begin
            // Dodaj bit do BCD
            if (BCD1 >= 5) BCD1 = BCD1 + 3;
            if (BCD2 >= 5) BCD2 = BCD2 + 3;

            // Przesuñ BCD w lewo o jeden bit
            BCD1 = BCD1 << 1;
            BCD1[0] = BCD2[3]; // Zapisz MSB z poprzedniego rejestru
            BCD2 = BCD2 << 1;
            BCD2[0] = BINARY[i]; // WprowadŸ nastêpny bit binarny
        end
    end
endmodule